#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config focus_follows_pointer true

bspc monitor HDMI-0 -d 'I' 'IV' 'VII' 
bspc monitor DP-1 -d 'II' 'V' 'VIII'
bspc monitor DP-2 -d 'III' 'VI' 'IX'

bspc config border_width         6
bspc config focused_border_color "#cc4738"
bspc config window_gap          8 #12

bspc config split_ratio          0.5

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle	 false

bspc rule -a Gimp desktop=^8
bspc rule -a virt-manager desktop=^7
bspc rule -a lazarus state=floating
bspc rule -a Lazarus state=floating
bspc rule -a android-studio state=floating border=off follow=on

picom -b -f &
nitrogen --restore &
/usr/bin/polkit-dumb-agent &
sxhkd -c $HOME/.config/sxhkd/sxhkdrc &
xsetroot -cursor_name left_ptr &
$HOME/.config/polybar/launch.sh &
wmname LG3D &
setxkbmap -option caps:swapescape &
sudo sh /home/zoey/Documents/vendorreset.sh
